name: Commit Timestamp

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
      - opened
      - synchronize
      - reopened

jobs:
  commit-timestamp:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo code
        uses: actions/checkout@v4

      - name: Get timestamps
        run: |
          # For latest commit hash
          HASH=$(git rev-parse HEAD)
          # ISO 8601 Format
          TIMESTAMP=$(git show -s --format=%ci $HASH)
          # Extract date, time, and offset
          DATE=$(echo $TIMESTAMP | cut -d' ' -f1)
          TIME=$(echo $TIMESTAMP | cut -d' ' -f2)
          OFFSET=$(echo $TIMESTAMP | cut -d' ' -f3)
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV
          echo "DATE=$DATE" >> $GITHUB_ENV
          echo "TIME=$TIME" >> $GITHUB_ENV
          echo "OFFSET=$OFFSET" >> $GITHUB_ENV
      - name: Add the comment to PR using curl
        if: github.event_name == 'pull_request'
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          TIMESTAMP="${{ env.TIMESTAMP }}"
          COMMENT="**Commit Timestamp**: ${TIMESTAMP}"
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -d "{\"body\": \"$COMMENT\"}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/comments"
